# Generated by Django 5.2.5 on 2025-09-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('uploaded_at_utc', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'RestaurantFiles',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSchedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
            options={
                'db_table': 'RestaurantSchedules',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('cuisine', 'Cuisine'), ('setting', 'Setting')], max_length=20)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='operatinghours',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Sysdiagrams',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='price_level',
            field=models.CharField(choices=[('budget-friendly', 'Budget-friendly'), ('average', 'Average'), ('expensive', 'Expensive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantfiles',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bite.restaurants'),
        ),
        migrations.AddField(
            model_name='restaurantschedules',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bite.restaurants'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='tags',
            field=models.ManyToManyField(related_name='restaurants', to='bite.tags'),
        ),
        migrations.AddConstraint(
            model_name='restaurants',
            constraint=models.CheckConstraint(condition=models.Q(('price_level__in', ['budget-friendly', 'average', 'expensive'])), name='valid_price_level'),
        ),
        migrations.DeleteModel(
            name='Cuisinetypes',
        ),
        migrations.DeleteModel(
            name='Operatinghours',
        ),
    ]
