# Generated by Django 5.2.5 on 2025-09-14 20:01

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0002_restaurantfiles_restaurantschedules_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='phone',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bite.restaurants'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bite.restaurants'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(default='Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
