# Generated by Django 5.2.5 on 2025-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0003_remove_restaurants_phone_restaurants_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
