# Generated by Django 5.2.5 on 2025-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0004_restaurants_city_alter_restaurants_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
