# Generated by Django 5.2.5 on 2025-09-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0004_restaurants_city_alter_restaurants_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantfiles',
            name='file_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
