# Generated by Django 5.2.5 on 2025-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0005_alter_restaurantfiles_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantfiles',
            name='file_url',
            field=models.URLField(max_length=1500),
        ),
    ]
