# Generated by Django 5.2.5 on 2025-10-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0006_alter_restaurantfiles_file_url'),
        ('bite', '0006_profile'),
    ]

    operations = [
    ]
