# Generated by Django 5.2.5 on 2025-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0008_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='booking_timestamp',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='status',
        ),
    ]
