# Generated by Django 5.2.5 on 2025-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0009_remove_reservations_booking_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='full_name',
            field=models.CharField(default='Rebecca Marusca', max_length=100),
            preserve_default=False,
        ),
    ]
