# Generated by Django 5.2.5 on 2025-10-07 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0010_reservations_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotlights', to='bite.restaurants')),
            ],
            options={
                'db_table': 'spotlight',
                'ordering': ['-created_at'],
            },
        ),
    ]
