# Generated by Django 5.2.5 on 2025-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bite', '0011_spotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
